module.exports = {
    armor: "INSERT INTO cvarmor (characterid, armorname, armordr, armorskilladj, armorbonus, armortrainingdef, armortrainrecovery, armortrainfatigue, armortraininit, armormiscdef, armormiscrecovery, armormiscinit, armormiscfatigue, armorbasedef,armorbaserecovery, armorbasefatiguemod, armorbaseinit)VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) ON CONFLICT (characterid)DO    UPDATE SET characterid = $2, armorname = $3, armordr = $4, armorskilladj = $5, armorbonus = $6, armortrainingdef = $7, armortrainrecovery = $8, armortrainfatigue = $9, armortraininit = $10, armormiscdef = $11, armormiscrecovery = $12, armormiscinit = $13, armormiscfatigue = $14,armorbasedef = $15, armorbaserecovery = $16, armorbasefatiguemod = $17, armorbaseinit = $18 where cvarmor.armorid = $1",
    damageone: "INSERT INTO damageone (characterid, title, value) VALUES($2, $3, $4)  ON CONFLICT (id) DO     UPDATE SET characterid = $2, title = $3, value = $4",
    damagetwo: "INSERT INTO weapontwo (characterid, trainattack, trainparry, trainrecovery, traindamage, miscattack, miscparry, miscrecovery, miscdamage, miscinit, name, basedamage, baserecovery, baseparry, basemeasure, type, bonus, traits, size) VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  ON CONFLICT (characterid) DO     UPDATE SET      characterid = $2, trainattack = $3, trainparry = $4, trainrecovery = $5, traindamage = $6, miscattack = $7, miscparry = $8, miscrecovery = $9, miscdamage = $10, miscinit = $11, name = $12, basedamage = $13, baserecovery = $14, baseparry = $15, basemeasure = $16, type = $17, bonus = $18, traits = $19, size = $20",
    shield: "INSERT INTO cvshield (characterid, shieldname, shielddr, shieldsize, shieldcover, shieldbonus, shieldbasedef, shieldbaseparry, shieldbasefatigue, shieldbasebreak, shieldtraindef, shieldtrainparry, shieldtrainfatigue, shieldtrainbreak, shieldmiscdef, shieldmiscparry, shieldmiscbreak,shieldmiscfatigue, shieldflanks) VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  ON CONFLICT (characterid) DO UPDATE SET  characterid = $2, shieldname = $3, shielddr = $4, shieldsize = $5, shieldcover = $6, shieldbonus = $7, shieldbasedef = $8, shieldbaseparry = $9, shieldbasefatigue = $10, shieldbasebreak = $11, shieldtraindef = $12, shieldtrainparry = $13, shieldtrainfatigue = $14, shieldtrainbreak = $15, shieldmiscdef = $16, shieldmiscparry = $17, shieldmiscbreak = $18,shieldmiscfatigue = $19, shieldflanks = $20 where cvshield.shieldid = $1",
    skillscombat: "INSERT INTO cvcombatskills (characterid, skill, cost, rank) VALUES($2, $3, $4, $5)  ON CONFLICT (id) DO UPDATE SET characterid = $2, skill = $3, cost = $4, rank = $5",
    skillsuitescombat: "insert into cvcharactercombatskillsuites (combatskillsuiteid, characterid, rank, trained) values ($1, $2, $3, $4)",
    weaponfour: "INSERT INTO weaponfour (characterid, trainattack, trainrecovery, traindamage, miscattack, miscrecovery, miscdamage, miscinit, name, basedamage, baserecovery, type, bonus, traits, size) VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)  ON CONFLICT (characterid) DO     UPDATE SET      characterid = $2, trainattack = $3, trainrecovery = $4, traindamage = $5, miscattack = $6, miscrecovery = $7, miscdamage = $8, miscinit = $9, name = $10, basedamage = $11, baserecovery = $12, type = $13, bonus = $14, traits = $15, size = $16 where weaponfour.weaponid = $1",
    weaponone: "INSERT INTO weaponone (characterid, trainattack, trainparry, trainrecovery, traindamage, miscattack, miscparry, miscrecovery, miscdamage, miscinit, name, basedamage, baserecovery, baseparry, basemeasure, type, bonus, traits, size)VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20) ON CONFLICT (characterid)DO    UPDATE SET     characterid = $2, trainattack = $3, trainparry = $4, trainrecovery = $5, traindamage = $6, miscattack = $7, miscparry = $8, miscrecovery = $9, miscdamage = $10, miscinit = $11, name = $12, basedamage = $13, baserecovery = $14, baseparry = $15, basemeasure = $16, type = $17, bonus = $18, traits = $19, size = $20 where weaponone.weaponid = $1",
    weaponthree: "INSERT INTO weaponthree (characterid, trainattack, trainparry, trainrecovery, traindamage, miscattack, miscparry, miscrecovery, miscdamage, miscinit, name, basedamage, baserecovery, baseparry, basemeasure, type, bonus, traits, size) VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  ON CONFLICT (characterid) DO     UPDATE SET      characterid = $2, trainattack = $3, trainparry = $4, trainrecovery = $5, traindamage = $6, miscattack = $7, miscparry = $8, miscrecovery = $9, miscdamage = $10, miscinit = $11, name = $12, basedamage = $13, baserecovery = $14, baseparry = $15, basemeasure = $16, type = $17, bonus = $18, traits = $19, size = $20 where weaponthree.weaponid = $1",
    weapontwo: "INSERT INTO weapontwo (characterid, trainattack, trainparry, trainrecovery, traindamage, miscattack, miscparry, miscrecovery, miscdamage, miscinit, name, basedamage, baserecovery, baseparry, basemeasure, type, bonus, traits, size) VALUES($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)  ON CONFLICT (characterid) DO     UPDATE SET      characterid = $2, trainattack = $3, trainparry = $4, trainrecovery = $5, traindamage = $6, miscattack = $7, miscparry = $8, miscrecovery = $9, miscdamage = $10, miscinit = $11, name = $12, basedamage = $13, baserecovery = $14, baseparry = $15, basemeasure = $16, type = $17, bonus = $18, traits = $19, size = $20 where weapontwo.weaponid = $1",
}